### ISSUE TITLE
Automate login codes for "linked login code for OSE" option

### ISSUE THREAD

**Issue by sophiebyouthtruth** [cep-repo/YT-tools#12]
Jeremy's program automates making login codes for normal OSE and FFT situations. Occasionally, a client will take an OSE survey but need to link the randomized login codes to student IDs. In this case, there is no current way to automate this and requires manual work to create excel login code files AND panels for every school that needs this. I can explain more, but we have a 20 school district coming up that would like linked login codes to their OSE survey and it would be great if we could automate this process.

**Comment by cepbrian** [comment]
Plan, run as if it's OSE then run as if it's FFT. Use the OSE panel, and the FFT login codes. May need to copy column from FFT panel into OSE panel.

**Comment by sophiebyouthtruth** [comment]
Update - Brian's new "-f" addition works great, except something strange is happening with the correct login codes being attached to the panel and excel login code format. When we tried this with alpha, the program generated an ose pdf'd version of login codes, and the fft excel version of login codes attached to student IDs that we wanted. However, the ose login codes somehow were the ones that appeared in the panel, so the pdf ones are the only login codes that work. We need the fft excel version of login codes that are linked to student IDs to work instead (and therefore need them in the panel to go into the survey). We need this done by 4/22. Thanks!

**Comment by cepbrian** [comment]
It appears that that problem was from residual files left around. When I run this in a fresh output directory, it appears to work.
