### ISSUE TITLE
Urgent - (due Friday) fam/staff jsons not generating correctly. 

### ISSUE THREAD

**Issue by sophiebyouthtruth** [cep-repo/YT-tools#18]
We went through the whole process on Jeremy's branch "db_insert" to create a json for a staff survey. While there were no errors, the json does not seem to be complete. Therefore, when we uploaded it into the ORS, it created an empty report. 

What I've looked into:
d.csv looks normal. I think it downloaded the data normally. 
the seg files and agg files also look normal, I think.
the VAR files are EMPTY. This might be it? 

One other idea:
Family surveys and staff surveys are separate things. I noticed the d.csv downloaded both family and staff data for middle schools instead of just staff. This goes for all the seg and agg files. This does make sense given Jeremy just created "fs" as an option as a YDEA production environment, but I wonder if the fact that the staff surveys have no family data and the family surveys have no staff data is messing something up. 

Use this as example: 
Dropbox (CEP)\YouthTruth\Report Production\_YDEA Archive\_FamilyStaff\Evergreen Staff\fs\ms\schools\Leyva Staff16MR

See empty report it created (the red lines around every place where there should be a chart indicate there is no data) - https://youthtruth.surveyresults.org/admin/report_sections/243062

environment - fs, ms, school_report

**Comment by cepbrian** [comment]
This should be in YDEA. I'll move it.
