### ISSUE TITLE
Cannot Run Survey Admin Script

### ISSUE THREAD

**Issue by joshyouthtruth** [cep-repo/YT-tools#19]
![4 27](https://cloud.githubusercontent.com/assets/16355348/14864377/7808c08e-0c6e-11e6-8936-02e991e03d92.JPG)

Running into this issue on the first step of survey administration.
Perhaps it relates to Jeremy's Salesforce (and it not existing now?)

**Comment by sophiebyouthtruth** [comment]
This is the error we both get when we run the get_profiled_list.py script.

**Comment by cepbrian** [comment]
It's looking for a field "FFT_Linked_Login_Code" in the salesforce. Does that not exist?

**Comment by joshyouthtruth** [comment]
Can confirm that a field exists under the "Additional Information" Tab at the Opportunity Level called "Linked Login Codes?"

**Comment by cepbrian** [comment]
but not FFT Linked Login Codes?

**Comment by joshyouthtruth** [comment]
Not that I see...perhaps there's a language mismatch?

FFT will always have linked login codes by nature of how the survey works (since it matches students to their teachers). The "Linked Login Codes" field is what we use to designate that OSE clients want to link their login codes as well.

**Comment by cepbrian** [comment]
It's looking for a custom field "FFT_Linked_Login_Codes" If that's not correct, we need to figure out if it's the salesforce, or the YTTools that's in error.

**Comment by joshyouthtruth** [comment]
My guess is YT Tools...FFT Linked Login Codes doesn't make much sense as a field

**Comment by sophiebyouthtruth** [comment]
Get_profiled_list should pull this list: Dropbox (CEP)\YouthTruth\Survey Administration\YouthTruthTools\SchoolProfiles\ProfiledSchools.csv.

There is a column in the ProfiledSchools.csv called “LinkedLoginCodes” but not “FFT Linked Login Codes.” This is a necessary column. It pulls from the “Linked Login Codes?” directly from Salesforce. Does this naming mismatch have anything to do with your new “-f” function, Brian?

**Comment by cepbrian** [comment]
Should work now.
