### ISSUE TITLE
Urgent - (due Friday) -f not making linked login codes. 

### ISSUE THREAD

**Issue by sophiebyouthtruth** [cep-repo/YT-tools#21]
Hey Brian,

The new -f feature you made works great to make the correct panel (attaches the roster info with student IDs to the panel) but is still creating OSE style login codes.

Here is the folder Josh has been working out of: Dropbox (CEP)\YouthTruth\Survey Administration\ClientFolders\Raise Your Hand Texas\LoginCodes

Raise Your Hand Texas is a district with 19 schools that all need to have linked login codes for their OSE surveys. They are due by Monday morning, so best to have them done by end of day Friday. 

These login codes were created with the create_panel.py script where he also appended an -f. The panels (Dropbox (CEP)\YouthTruth\Survey Administration\ClientFolders\Raise Your Hand Texas\Panels) look like they should. Per our conversation when I was in Boston, the login codes should be excel documents that look like this (below) where the student ID is attached to a login code. Instead, the login codes are coming in as PDFs like they should for any other OSE survey. The difference is this OSE survey needs linked login codes.

Dropbox (CEP)\YouthTruth\Survey Administration\ClientFolders\Alpha Public Schools\LoginCodes\alpha_jose_hernandez_middle_school_-_may_2016_logincodes_final

**Comment by cepbrian** [comment]
How are these generated again?

**Comment by sophiebyouthtruth** [comment]
These are generated during the create_panel step. You added the -f function to go along with this step.

On Apr 29, 2016, at 7:37 AM, Brian Postow <notifications@github.com<mailto:notifications@github.com>> wrote:


How are these generated again?

-

**Comment by cepbrian** [comment]
Sorry, I should be more specific, can you give me a command line, pointer to an infile, and what row I should be using?

**Comment by cepbrian** [comment]
The output looks correct to me. What is wrong with Alpha\ Jose\ Hernandez\ Middle\ School\ -\ May\ 2016_logincodes.xls?

**Comment by sophiebyouthtruth** [comment]
I'll be in the office soon, but the in file is the profiled school csv, and you can use any rowid in there that is part of raise your hand Texas. You might need to change the directory of the roster data file since right now it's a c:/josh. Command line is create_panel.py

Sent from my iPhone

On Apr 29, 2016, at 8:07 AM, Brian Postow <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I should be more specific, can you give me a command line, pointer to an infile, and what row I should be using?

-

**Comment by sophiebyouthtruth** [comment]
Hi Brian,

That's the example I was showing you that is correct. The example that josh was working with is the raise your hand Texas folder.



On Apr 29, 2016, at 8:16 AM, Brian Postow <notifications@github.com<mailto:notifications@github.com>> wrote:


The output looks correct to me. What is wrong with Alpha\ Jose\ Hernandez\ Middle\ School\ -\ May\ 2016_logincodes.xls?

-

**Comment by cepbrian** [comment]
ah. Where is the profiled school csv?I see it for the Alpha, but not for the Raise.

**Comment by cepbrian** [comment]
And the commandline isn't just "create_panel.py" 

When I ask for a commandline I'm asking for the full line you enter:

python [PATH]/create_panel.py -i <inputfile> -o <outdir> -f -rowid <row>

What inputfile and row are you testing with?
